name: workflow name is Pythonnn Versions
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pythonnn: [3.8, 3.9, 3.10]
    steps:
      - run: echo "Testing on Python ${{ matrix.pythonnn }}"
